name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - name: Build
        run: yarn build
